In [9]:
import pandas as pd
import numpy as np
import warnings
import os
from pyECLAT import Example1, ECLAT
from mlxtend.frequent_patterns import apriori, association_rules

In [10]:
path = f'{os.getcwd()}\\Tratamento e Analise\\Dados\\'
warnings.filterwarnings('ignore')

dados = pd.read_csv(path + 'dados_tratados.csv', sep = ';')
dados.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [11]:
associacao = apriori(dados, min_support = 0.05, use_colnames=True)
associacao.sort_values('support', ascending = False)
associacao.head()

    support        itemsets
0  0.078502      (UHT-milk)
1  0.119548          (beef)
2  0.079785       (berries)
3  0.062083     (beverages)
4  0.158799  (bottled beer)

In [12]:
#----Support (Suporte):O suporte varia de 0 a 1.
#O suporte indica a frequÃªncia absoluta com que um conjunto de itens (A e B juntos) aparece nas transaÃ§Ãµes.

#----Confidence (ConfianÃ§a):A confianÃ§a varia de 0 a 1.
#A confianÃ§a mede a probabilidade de que o consequente (B) ocorra em uma transaÃ§Ã£o, dado que o antecedente (A) tambÃ©m ocorreu.
#Quanto maior a confianÃ§a, mais forte Ã© a associaÃ§Ã£o entre A e B.
#Uma confianÃ§a de 1 indica que B sempre ocorre quando A ocorre.

#----Lift (ElevaÃ§Ã£o): O lift varia de 0 a infinito.
#O lift compara a frequÃªncia observada de A e B ocorrendo juntos com a frequÃªncia esperada se a associaÃ§Ã£o fosse independente.
#Um lift maior que 1 indica uma associaÃ§Ã£o positiva entre A e B (eles ocorrem juntos mais frequentemente do que o esperado ao 
#acaso).Um lift igual a 1 indica independÃªncia (sem associaÃ§Ã£o).Um lift menor que 1 indica uma associaÃ§Ã£o negativa 
#(A e B ocorrem juntos menos frequentemente do que o esperado ao acaso).

#----Leverage (Alavancagem): A alavancagem pode variar de -1 a 1.
#A alavancagem mede a diferenÃ§a entre a frequÃªncia observada de A e B ocorrendo juntos e a frequÃªncia esperada se fossem indepen
#dentes. Um valor positivo de alavancagem indica uma associaÃ§Ã£o positiva entre A e B. Um valor negativo indica uma associaÃ§Ã£o 
#negativa ou ausÃªncia de associaÃ§Ã£o.

#----Conviction (ConvicÃ§Ã£o): A convicÃ§Ã£o pode variar de 0 a infinito.
# A convicÃ§Ã£o mede o grau de dependÃªncia do consequente (B) na presenÃ§a do antecedente (A). Quanto maior a convicÃ§Ã£o, mais 
#forte Ã© a dependÃªncia de B em relaÃ§Ã£o a A. Uma convicÃ§Ã£o de 1 indica independÃªncia (ausÃªncia de associaÃ§Ã£o entre A e B).

In [13]:
regras = association_rules(associacao, metric = 'lift')
regras.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(beef),(other vegetables),0.119548,0.376603,0.050795,0.424893,1.128223,0.005773,1.083966,0.129082
1,(other vegetables),(beef),0.376603,0.119548,0.050795,0.134877,1.128223,0.005773,1.017719,0.182309
2,(beef),(whole milk),0.119548,0.458184,0.064135,0.536481,1.170886,0.009360,1.168919,0.165762
3,(whole milk),(beef),0.458184,0.119548,0.064135,0.139978,1.170886,0.009360,1.023754,0.269364
4,(bottled beer),(other vegetables),0.158799,0.376603,0.068497,0.431341,1.145345,0.008692,1.096257,0.150857

In [15]:
regras.sort_values('confidence', ascending = False).head(5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
194,"(bottled water, other vegetables)",(whole milk),0.093894,0.458184,0.056183,0.598361,1.305941,0.013162,1.349012,0.258544
237,"(other vegetables, yogurt)",(whole milk),0.120318,0.458184,0.071832,0.597015,1.303003,0.016704,1.344507,0.264348
249,"(rolls/buns, yogurt)",(whole milk),0.111339,0.458184,0.065931,0.592166,1.292420,0.014917,1.328521,0.254605
206,"(rolls/buns, other vegetables)",(whole milk),0.146742,0.458184,0.082093,0.559441,1.220996,0.014859,1.229837,0.212124
255,"(soda, yogurt)",(whole milk),0.097486,0.458184,0.054387,0.557895,1.217622,0.009720,1.225537,0.198033